// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/cannedmessages.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.CannedMessageModuleConfig
 */
export const CannedMessageModuleConfig = proto3.makeMessageType(
  "meshtastic.CannedMessageModuleConfig",
  () => [
    { no: 1, name: "messages", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

