// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/cannedmessages.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.CannedMessageModuleConfig
 */
export declare class CannedMessageModuleConfig extends Message<CannedMessageModuleConfig> {
  /**
   *
   * Predefined messages for canned message module separated by '|' characters.
   *
   * @generated from field: string messages = 1;
   */
  messages: string;

  constructor(data?: PartialMessage<CannedMessageModuleConfig>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "meshtastic.CannedMessageModuleConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): CannedMessageModuleConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): CannedMessageModuleConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): CannedMessageModuleConfig;

  static equals(a: CannedMessageModuleConfig | PlainMessage<CannedMessageModuleConfig> | undefined, b: CannedMessageModuleConfig | PlainMessage<CannedMessageModuleConfig> | undefined): boolean;
}

