// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/mqtt.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { MeshPacket } from "./mesh_pb.js";

/**
 *
 * This message wraps a MeshPacket with extra metadata about the sender and how it arrived.
 *
 * @generated from message meshtastic.ServiceEnvelope
 */
export const ServiceEnvelope = proto3.makeMessageType(
  "meshtastic.ServiceEnvelope",
  () => [
    { no: 1, name: "packet", kind: "message", T: MeshPacket },
    { no: 2, name: "channel_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "gateway_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

