// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/rtttl.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.RTTTLConfig
 */
export declare class RTTTLConfig extends Message<RTTTLConfig> {
  /**
   *
   * Ringtone for PWM Buzzer in RTTTL Format.
   *
   * @generated from field: string ringtone = 1;
   */
  ringtone: string;

  constructor(data?: PartialMessage<RTTTLConfig>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "meshtastic.RTTTLConfig";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): RTTTLConfig;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): RTTTLConfig;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): RTTTLConfig;

  static equals(a: RTTTLConfig | PlainMessage<RTTTLConfig> | undefined, b: RTTTLConfig | PlainMessage<RTTTLConfig> | undefined): boolean;
}

