// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/rtttl.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 *
 * Canned message module configuration.
 *
 * @generated from message meshtastic.RTTTLConfig
 */
export const RTTTLConfig = proto3.makeMessageType(
  "meshtastic.RTTTLConfig",
  () => [
    { no: 1, name: "ringtone", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

