// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/xmodem.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message meshtastic.XModem
 */
export const XModem = proto3.makeMessageType(
  "meshtastic.XModem",
  () => [
    { no: 1, name: "control", kind: "enum", T: proto3.getEnumType(XModem_Control) },
    { no: 2, name: "seq", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "crc16", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "buffer", kind: "scalar", T: 12 /* ScalarType.BYTES */ },
  ],
);

/**
 * @generated from enum meshtastic.XModem.Control
 */
export const XModem_Control = proto3.makeEnum(
  "meshtastic.XModem.Control",
  [
    {no: 0, name: "NUL"},
    {no: 1, name: "SOH"},
    {no: 2, name: "STX"},
    {no: 4, name: "EOT"},
    {no: 6, name: "ACK"},
    {no: 21, name: "NAK"},
    {no: 24, name: "CAN"},
    {no: 26, name: "CTRLZ"},
  ],
);

