// @generated by protoc-gen-es v1.2.0
// @generated from file meshtastic/xmodem.proto (package meshtastic, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message meshtastic.XModem
 */
export declare class XModem extends Message<XModem> {
  /**
   * @generated from field: meshtastic.XModem.Control control = 1;
   */
  control: XModem_Control;

  /**
   * @generated from field: uint32 seq = 2;
   */
  seq: number;

  /**
   * @generated from field: uint32 crc16 = 3;
   */
  crc16: number;

  /**
   * @generated from field: bytes buffer = 4;
   */
  buffer: Uint8Array;

  constructor(data?: PartialMessage<XModem>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "meshtastic.XModem";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): XModem;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): XModem;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): XModem;

  static equals(a: XModem | PlainMessage<XModem> | undefined, b: XModem | PlainMessage<XModem> | undefined): boolean;
}

/**
 * @generated from enum meshtastic.XModem.Control
 */
export declare enum XModem_Control {
  /**
   * @generated from enum value: NUL = 0;
   */
  NUL = 0,

  /**
   * @generated from enum value: SOH = 1;
   */
  SOH = 1,

  /**
   * @generated from enum value: STX = 2;
   */
  STX = 2,

  /**
   * @generated from enum value: EOT = 4;
   */
  EOT = 4,

  /**
   * @generated from enum value: ACK = 6;
   */
  ACK = 6,

  /**
   * @generated from enum value: NAK = 21;
   */
  NAK = 21,

  /**
   * @generated from enum value: CAN = 24;
   */
  CAN = 24,

  /**
   * @generated from enum value: CTRLZ = 26;
   */
  CTRLZ = 26,
}

